### ISSUE TITLE
what's the meanning of mask and terminated?

### ISSUE THREAD

**Issue by Kabibi** [oxwhirl/pymarl#16]
According to my understanding of `terminated` and `mask`, `terminated` is a vector consist of 0s and only one 1. 1 means the terminated time step of the episode. 

https://github.com/oxwhirl/pymarl/blob/eaf6b063822e2bdf1992d72dc159a500f235dbc4/src/learners/q_learner.py#L43

`mask` is, for example, [1,1,1,1,0,0], which tells that the episode length is 4. Then the corresponding `terminated` is [0,0,0,1,0,0]. 
Then 
```python
mask[:, 1:] is [1,1,1,0,0]
1 - terminated[:, :-1] is [1,1,1,0,1] 
mask[:, 1:] * (1 - terminated[:, :-1]) is [1,1,1,0,0]
```
So after performing `mask[:, 1:] = mask[:, 1:] * (1 - terminated[:, :-1])`, `mask` is still [1,1,1,1,0,0]. This line of code doesn't change `mask`. Then what does this line of code do?  Thanks.

I am also confused about the dimension of `mask` and `terminated` in your code. They do not contain the dimension of the number of agents. Can you explain? Thanks :)

**Comment by Greg-Farquhar** [comment]
This is to correctly handle the cases where either (a) the episode is not terminated, but has been truncated due to the timestep limit in the environment, and (b) the episode has been terminated in the final timestep. In either case "filled" is all ones, but the mask needs to be different.

For your other question, since these are cooperative tasks all agents experience the same rewards and terminal states. As a result, `mask` and `terminal` don't require an agent dimension. It shouldn't be too difficult to add an agent dimension if you want to adapt the code for a mixed cooperative-competitive task where the agents have different terminal states.

**Comment by GoingMyWay** [comment]
> This is to correctly handle the cases where either (a) the episode is not terminated, but has been truncated due to the timestep limit in the environment, and (b) the episode has been terminated in the final timestep. In either case "filled" is all ones, but the mask needs to be different.
> 
> For your other question, since these are cooperative tasks all agents experience the same rewards and terminal states. As a result, `mask` and `terminal` don't require an agent dimension. It shouldn't be too difficult to add an agent dimension if you want to adapt the code for a mixed cooperative-competitive task where the agents have different terminal states.

@Greg-Farquhar Thank you for your answer. My question here is why slicing the rewards, actions, terminated and mask in  https://github.com/oxwhirl/pymarl/blob/master/src/learners/q_learner.py#L39 with `-1'?

```Python
        rewards = batch["reward"][:, :-1]
        actions = batch["actions"][:, :-1]
        terminated = batch["terminated"][:, :-1].float()
        mask = batch["filled"][:, :-1].float()
        mask[:, 1:] = mask[:, 1:] * (1 - terminated[:, :-1])
```
