### ISSUE TITLE
I can't find the place where you compute "battle_won_mean", where is the logger of  "battle_won_mean"?

### ISSUE THREAD

**Issue by Gezx** [oxwhirl/pymarl#47]

**Comment by GJHall** [comment]
I don't really understand how self.stats works but I believe this is where the calculation occurs:

https://github.com/oxwhirl/pymarl/blob/29ac1a2db8a9174dac1462bace5e800538f48313/src/utils/logging.py#L48

**Comment by tabzraz** [comment]
battle_won is returned from the environment (as part of the env_info dictionary).

Any data from `env_info` (information from environment about the most recent episodes being run) is added to `cur_stats` (info about all episodes since the last time it was logged). 
That's then logged using `_log` in the runner:
https://github.com/oxwhirl/pymarl/blob/29ac1a2db8a9174dac1462bace5e800538f48313/src/runners/episode_runner.py#L115
