### ISSUE TITLE
Qmix Performance Inconsistency

### ISSUE THREAD

**Issue by mzho7212** [oxwhirl/pymarl#52]
Hi, I'm currently running experiments on the scenario '3s5z' and '1c3s5z' and find there is a significant performance difference from the Qmix paper. (my experiment result is roughly 15% to 20% better than the paper regarding test won rate). So just wondering if there is any difference with the environment setting or algorithm change. 

Thank you so much.

**Comment by samvelyan** [comment]
The results that you get using this repository should coincide with the results from our [SMAC paper](https://arxiv.org/pdf/1902.04043.pdf). Although our earlier [QMIX paper](https://arxiv.org/pdf/1803.11485.pdf) features similar maps, many things have been slightly changed since the release of the [PyMARL framework](https://github.com/oxwhirl/pymarl) and [SMAC benchmark](https://github.com/oxwhirl/smac), such as agent observations, the structure of the maps, parameters of the mixing network of QMIX, etc.
